grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 3
      - 4
      - 5 
      - 1
      - 2
      - 6

      n_estimators:
      - 50
      - 100
      - 200
  module_2:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      random_state: 0
    search_param_grid:
      min_samples_leaf:
      - 2
      - 1
      - 3

      


  module_3:
    class: XGBClassifier
    module: xgboost
    params:
      verbose: 1
      n_estimators: 100 
      
    search_param_grid:
      max_depth:
      - 2
      - 4
      - 6   
      n_estimators:
      - 50
      - 100
      - 200

        


      
      


