grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 7
    verbose: 1
model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      verbose: 1
      n_jobs: 1
      oob_score: true
      min_samples_split: 2
      min_samples_leaf: 1
    search_param_grid:
      n_estimators:
      - 200
      
     
      

     
      






      

      

      


      
     


 
      
        


      
      


